//Leetcode 7-Feb-2022
/*
----------------------------------------------389. Find the Difference---------------------------------------------------
Easy

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
class Solution389 {
    public char findTheDifference(String s, String t) {
        char[] a=s.toCharArray();
        char[] b=t.toCharArray();
        int[] arr=new int[26];
        for(char ch:b){
            arr[ch-'a']++;
        }
        for(char ch:a){
            arr[ch-'a']--;
        }
        for(int i=0;i<26;i++){
            if(arr[i]==1) return (char)(i+97);
        }
        return 'a';
    }
}